Repository lambdaclass/starknet_in_rust, pull requests merged in 2023-07, with the labels that each got.

#714 Improve naming of internal transaction methods
  src/execution/execution_entry_point.rs
  src/execution/mod.rs
  src/syscalls/business_logic_syscall_handler.rs
  src/syscalls/syscall_response.rs
  src/transaction/declare.rs
  src/transaction/declare_v2.rs
  src/transaction/deploy.rs
  src/transaction/deploy_account.rs
  src/transaction/invoke_function.rs
  src/transaction/l1_handler.rs
Labels: Refactor

#715 Rename to block_context
  tests/internals.rs
Labels: Refactor

#769 Allow redeclare class
  src/transaction/declare.rs
Labels: bug

#783 fix: change order of arguments in fee transfer's calldata
  src/transaction/declare.rs
  src/transaction/error.rs
  src/transaction/fee.rs
  src/transaction/invoke_function.rs
  src/utils.rs
  tests/internals.rs
  tests/syscalls_errors.rs
Labels: bug

#778 Add documentation for gas_usage
  src/execution/gas_usage.rs
Labels: documentation

#818 Document InMemoryStateReader
  src/state/in_memory_state_reader.rs
Labels: documentation

#787 Update charge fee and add n_steps for reverted transactions
  src/definitions/constants.rs
  src/lib.rs
  src/testing/state.rs
  src/transaction/declare.rs
  src/transaction/declare_v2.rs
  src/transaction/deploy.rs
  src/transaction/deploy_account.rs
  src/transaction/fee.rs
  src/transaction/invoke_function.rs
  src/transaction/l1_handler.rs
  src/utils.rs
  tests/deploy_account.rs
  tests/internals.rs
Labels: 0.12.1

#835 Docs transaction_type
  src/definitions/transaction_type.rs
Labels: documentation
